[build]
base = "client"
command = "npm install --no-audit --no-fund && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_VERSION = "11.5.2"
NETLIFY_BUILD_DEBUG = "true"


